title: Dev with Kelvin
description: All things Software
author: "Kelvin Harron"
theme: minima
show_excerpts: true

base_url: /about
google_analytics: G-2X3D6YQR8G

twitter_username: kelvinharron
github_username: kelvinharron
rss: rss

minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - _pages/frontpage.markdown
  - _pages/about.markdown

include:
  - _pages